name: "❓ Question / 提问"
description: |
  Ask a question or get help.

  提出问题或寻求帮助。
title: "[Question] "
labels: ["question"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description / 描述"
    validations:
      required: true
